# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5289ade6ed4feb3fe4f399d6d6947794684f97cdf5edf1f3b6204937b1d6b1275dcfcf6db3cd1c62238ecc4cb62626411804f52b2f6b3af635f92b4bb8237951

test:
  secret_key_base: 9c8da7ef5b8458c76eaedaf89693c7ecc3b455951f8af1701f8b6ce5047cc2d6432db45285063d31036463ba5baff7d589c21fff710b402620b3506b597c0ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']>
  
